// 板橋週邊地區 SEO 落地頁資料
// 每個區生成一個 /[area]-repair 頁面，吃地區搜尋流量

export interface LocalArea {
  slug: string;        // URL 用，全英文 lowercase
  city: string;        // "新北市"
  district: string;    // "板橋區"
  zhName: string;      // "板橋"（簡稱）
  fullName: string;    // "新北市板橋區"
  description: string; // SEO meta description
  // 距離店家（板橋江子翠）
  distanceMin: number;
  // 在地特色／話題
  highlights: string[];
  // 鄰近的學區／商圈／知名地標
  landmarks: string[];
  // 此區常見送修裝置／需求（hand-tuned for relevance）
  popularServices: string[];
}

export const LOCAL_AREAS: LocalArea[] = [
  {
    slug: "banqiao",
    city: "新北市",
    district: "板橋區",
    zhName: "板橋",
    fullName: "新北市板橋區",
    description: "板橋手機維修首選 i時代．14 年技術．iPhone / iPad / MacBook / Switch 全方位維修．現場 30 分鐘完工",
    distanceMin: 0,
    highlights: ["門市所在地", "捷運江子翠站旁", "免運費送回"],
    landmarks: ["江子翠捷運站", "府中站", "大遠百", "板橋車站", "亞東醫院"],
    popularServices: ["iPhone 換螢幕", "電池更換", "進水救援", "MacBook 維修", "Switch 搖桿"],
  },
  {
    slug: "zhonghe",
    city: "新北市",
    district: "中和區",
    zhName: "中和",
    fullName: "新北市中和區",
    description: "中和手機維修推薦 i時代．距中和僅 10 分鐘．iPhone 換螢幕電池．Switch / iPad / MacBook 維修",
    distanceMin: 10,
    highlights: ["10 分鐘車程", "可搭捷運直達江子翠", "免運送回到府"],
    landmarks: ["環球購物中心", "南勢角站", "永安市場站", "華新街"],
    popularServices: ["iPhone 螢幕", "電池更換", "Android 維修", "iPad 螢幕"],
  },
  {
    slug: "yonghe",
    city: "新北市",
    district: "永和區",
    zhName: "永和",
    fullName: "新北市永和區",
    description: "永和手機維修選 i時代．15 分鐘到板橋門市．iPhone / Samsung / Google Pixel 全方位維修",
    distanceMin: 15,
    highlights: ["15 分鐘車程", "Pixel / Samsung 認證零件", "免費檢測"],
    landmarks: ["頂溪站", "樂華夜市", "Costco 中和店", "永和豆漿總店"],
    popularServices: ["iPhone 維修", "Samsung 換螢幕", "電池更換", "資料救援"],
  },
  {
    slug: "sanchong",
    city: "新北市",
    district: "三重區",
    zhName: "三重",
    fullName: "新北市三重區",
    description: "三重手機維修．i時代板橋門市 12 分鐘車程．iPhone / iPad / MacBook 認證零件．當日完工",
    distanceMin: 12,
    highlights: ["12 分鐘車程", "可搭捷運直達", "急件 30 分鐘修好"],
    landmarks: ["菜寮站", "三重站", "台北橋", "三和夜市"],
    popularServices: ["iPhone 螢幕", "電池", "進水救援", "MacBook 維修"],
  },
  {
    slug: "shulin",
    city: "新北市",
    district: "樹林區",
    zhName: "樹林",
    fullName: "新北市樹林區",
    description: "樹林手機維修 i時代．樹林到板橋僅 10 分鐘．iPhone / Android 換螢幕電池．現場完工",
    distanceMin: 10,
    highlights: ["10 分鐘車程", "捷運直達板橋", "現場維修"],
    landmarks: ["樹林車站", "樹林夜市", "大同山"],
    popularServices: ["iPhone 螢幕", "電池更換", "Android 維修", "Switch"],
  },
  {
    slug: "xinzhuang",
    city: "新北市",
    district: "新莊區",
    zhName: "新莊",
    fullName: "新北市新莊區",
    description: "新莊手機維修．i時代板橋門市 15 分鐘車程．iPhone / Samsung / Pixel 認證維修．Dyson 也修",
    distanceMin: 15,
    highlights: ["15 分鐘車程", "捷運中和新蘆線直達", "Dyson / Switch 也修"],
    landmarks: ["新莊站", "輔大站", "新莊夜市", "幸福水漾公園"],
    popularServices: ["iPhone 螢幕", "電池", "Dyson 維修", "Switch"],
  },
  {
    slug: "tucheng",
    city: "新北市",
    district: "土城區",
    zhName: "土城",
    fullName: "新北市土城區",
    description: "土城手機維修 i時代．8 分鐘車程到板橋．iPhone / iPad 換螢幕電池．認證電池更耐用",
    distanceMin: 8,
    highlights: ["8 分鐘車程", "可搭捷運", "急件當日完工"],
    landmarks: ["海山站", "土城站", "永寧站", "清水祖師廟"],
    popularServices: ["iPhone 維修", "iPad 螢幕", "電池更換"],
  },
  {
    slug: "luzhou",
    city: "新北市",
    district: "蘆洲區",
    zhName: "蘆洲",
    fullName: "新北市蘆洲區",
    description: "蘆洲手機維修．i時代 18 分鐘車程．iPhone / Samsung / Pixel 換螢幕．免運送回",
    distanceMin: 18,
    highlights: ["18 分鐘車程", "捷運蘆洲線直達", "免運送回"],
    landmarks: ["蘆洲站", "三民高中站", "湧蓮寺", "蘆洲夜市"],
    popularServices: ["iPhone 螢幕", "電池", "Samsung 維修"],
  },
  // === 新北市其他區（≤ 30 分鐘車程）===
  {
    slug: "xindian",
    city: "新北市",
    district: "新店區",
    zhName: "新店",
    fullName: "新北市新店區",
    description: "新店手機維修．i時代板橋門市 25 分鐘車程．iPhone / Samsung / Pixel 維修．現場完工",
    distanceMin: 25,
    highlights: ["25 分鐘車程", "捷運松山新店線直達", "現場維修"],
    landmarks: ["新店站", "大坪林站", "七張站", "碧潭"],
    popularServices: ["iPhone 螢幕", "電池", "iPad 維修"],
  },
  {
    slug: "wugu",
    city: "新北市",
    district: "五股區",
    zhName: "五股",
    fullName: "新北市五股區",
    description: "五股手機維修．i時代 20 分鐘車程．iPhone / Android 換螢幕電池．認證零件",
    distanceMin: 20,
    highlights: ["20 分鐘車程", "65 線快速到", "現場維修"],
    landmarks: ["五股工業區", "成蘆橋", "五股自行車道"],
    popularServices: ["iPhone 維修", "電池", "Android 螢幕"],
  },
  {
    slug: "taishan",
    city: "新北市",
    district: "泰山區",
    zhName: "泰山",
    fullName: "新北市泰山區",
    description: "泰山手機維修．i時代板橋門市 18 分鐘車程．iPhone / iPad / MacBook 維修．免運送回",
    distanceMin: 18,
    highlights: ["18 分鐘車程", "捷運泰山貴和站", "MacBook 也修"],
    landmarks: ["泰山貴和站", "輔大站", "義學國小"],
    popularServices: ["iPhone 螢幕", "電池", "MacBook 維修"],
  },
  {
    slug: "linkou",
    city: "新北市",
    district: "林口區",
    zhName: "林口",
    fullName: "新北市林口區",
    description: "林口手機維修．i時代 30 分鐘車程．iPhone / Samsung / Switch 維修．Dyson 也修",
    distanceMin: 30,
    highlights: ["30 分鐘車程", "Outlets 商圈鄰近", "Switch 維修"],
    landmarks: ["林口三井 Outlet", "長庚醫院", "林口運動公園"],
    popularServices: ["iPhone 維修", "Switch 搖桿", "Dyson", "iPad"],
  },
  {
    slug: "sanxia",
    city: "新北市",
    district: "三峽區",
    zhName: "三峽",
    fullName: "新北市三峽區",
    description: "三峽手機維修．i時代 25 分鐘車程．iPhone / Android 換螢幕電池．急件當日完工",
    distanceMin: 25,
    highlights: ["25 分鐘車程", "鄰近台北大學", "急件 30 分鐘"],
    landmarks: ["三峽老街", "台北大學", "鳶山", "祖師廟"],
    popularServices: ["iPhone 螢幕", "電池", "Android 維修"],
  },
  {
    slug: "yingge",
    city: "新北市",
    district: "鶯歌區",
    zhName: "鶯歌",
    fullName: "新北市鶯歌區",
    description: "鶯歌手機維修．i時代 22 分鐘車程．iPhone / 三星換螢幕電池．免運送回",
    distanceMin: 22,
    highlights: ["22 分鐘車程", "可火車直達板橋", "免運送回"],
    landmarks: ["鶯歌老街", "陶瓷博物館", "鶯歌火車站"],
    popularServices: ["iPhone 螢幕", "電池", "Samsung"],
  },
  {
    slug: "xizhi",
    city: "新北市",
    district: "汐止區",
    zhName: "汐止",
    fullName: "新北市汐止區",
    description: "汐止手機維修．i時代板橋門市 30 分鐘車程．iPhone / iPad / MacBook 認證維修",
    distanceMin: 30,
    highlights: ["30 分鐘車程", "汐科 / 遠雄商圈鄰近", "MacBook 維修"],
    landmarks: ["汐止車站", "汐科站", "遠雄 U-Town", "Costco 汐止店"],
    popularServices: ["iPhone 維修", "MacBook", "iPad"],
  },
  {
    slug: "tamsui",
    city: "新北市",
    district: "淡水區",
    zhName: "淡水",
    fullName: "新北市淡水區",
    description: "淡水手機維修．i時代 35 分鐘車程．iPhone / Samsung / Pixel 維修．免運送回到府",
    distanceMin: 35,
    highlights: ["35 分鐘車程", "捷運淡水線直達", "免運送回"],
    landmarks: ["淡水老街", "漁人碼頭", "淡水大學", "紅毛城"],
    popularServices: ["iPhone 螢幕", "電池", "Samsung 維修"],
  },
  {
    slug: "shenkeng",
    city: "新北市",
    district: "深坑區",
    zhName: "深坑",
    fullName: "新北市深坑區",
    description: "深坑手機維修．i時代板橋 35 分鐘車程．iPhone / Android 換螢幕．急件當日完工",
    distanceMin: 35,
    highlights: ["35 分鐘車程", "急件當日完工", "免運送回"],
    landmarks: ["深坑老街", "深坑國中", "石碇山區"],
    popularServices: ["iPhone 維修", "電池"],
  },
  // === 台北市（捷運直達或交通方便區）===
  {
    slug: "wanhua",
    city: "台北市",
    district: "萬華區",
    zhName: "萬華",
    fullName: "台北市萬華區",
    description: "萬華手機維修．i時代板橋門市 8 分鐘車程．iPhone / iPad / Switch 維修．急件 30 分鐘",
    distanceMin: 8,
    highlights: ["8 分鐘車程", "板南線直達", "急件 30 分鐘"],
    landmarks: ["龍山寺站", "西門町", "萬華車站", "華西街夜市"],
    popularServices: ["iPhone 螢幕", "電池", "Switch"],
  },
  {
    slug: "zhongzheng",
    city: "台北市",
    district: "中正區",
    zhName: "中正",
    fullName: "台北市中正區",
    description: "中正區手機維修．i時代 15 分鐘車程．iPhone / MacBook / iPad 認證維修",
    distanceMin: 15,
    highlights: ["15 分鐘車程", "板南線直達", "MacBook 維修"],
    landmarks: ["台北車站", "中正紀念堂", "西門町", "古亭站"],
    popularServices: ["iPhone 維修", "MacBook", "iPad", "電池"],
  },
  {
    slug: "datong",
    city: "台北市",
    district: "大同區",
    zhName: "大同",
    fullName: "台北市大同區",
    description: "大同區手機維修．i時代 18 分鐘車程．iPhone / Samsung 換螢幕．免運送回",
    distanceMin: 18,
    highlights: ["18 分鐘車程", "捷運轉乘方便", "免運送回"],
    landmarks: ["大橋頭站", "圓山站", "迪化街", "寧夏夜市"],
    popularServices: ["iPhone 螢幕", "電池", "Samsung 維修"],
  },
  {
    slug: "zhongshan",
    city: "台北市",
    district: "中山區",
    zhName: "中山",
    fullName: "台北市中山區",
    description: "中山區手機維修．i時代板橋門市 20 分鐘車程．iPhone / MacBook / iPad 維修",
    distanceMin: 20,
    highlights: ["20 分鐘車程", "中山商圈鄰近", "MacBook 維修"],
    landmarks: ["中山站", "雙連站", "南京復興", "晴光商圈"],
    popularServices: ["iPhone 維修", "MacBook", "電池"],
  },
  {
    slug: "daan",
    city: "台北市",
    district: "大安區",
    zhName: "大安",
    fullName: "台北市大安區",
    description: "大安區手機維修．i時代板橋 22 分鐘車程．iPhone / iPad / MacBook 認證維修",
    distanceMin: 22,
    highlights: ["22 分鐘車程", "東區商圈鄰近", "認證原廠零件"],
    landmarks: ["忠孝復興", "大安森林公園", "東門站", "公館"],
    popularServices: ["iPhone 維修", "MacBook", "iPad"],
  },
  {
    slug: "songshan",
    city: "台北市",
    district: "松山區",
    zhName: "松山",
    fullName: "台北市松山區",
    description: "松山區手機維修．i時代 28 分鐘車程．iPhone / Samsung / iPad 維修．免運送回",
    distanceMin: 28,
    highlights: ["28 分鐘車程", "松山機場鄰近", "免運送回"],
    landmarks: ["松山機場", "饒河夜市", "南京三民站", "松山車站"],
    popularServices: ["iPhone 螢幕", "電池", "Samsung 維修"],
  },
  {
    slug: "xinyi",
    city: "台北市",
    district: "信義區",
    zhName: "信義",
    fullName: "台北市信義區",
    description: "信義區手機維修．i時代 30 分鐘車程．iPhone 全方位維修．急件可現場完工",
    distanceMin: 30,
    highlights: ["30 分鐘車程", "信義商圈鄰近", "MacBook 維修"],
    landmarks: ["信義 101", "市府站", "象山", "三創"],
    popularServices: ["iPhone 維修", "MacBook", "電池"],
  },
  {
    slug: "wenshan",
    city: "台北市",
    district: "文山區",
    zhName: "文山",
    fullName: "台北市文山區",
    description: "文山區手機維修．i時代板橋門市 25 分鐘車程．iPhone / Switch / Dyson 維修",
    distanceMin: 25,
    highlights: ["25 分鐘車程", "鄰近政大世新", "Switch / Dyson 修"],
    landmarks: ["木柵站", "公館站", "政治大學", "貓空"],
    popularServices: ["iPhone 維修", "Switch 搖桿", "Dyson"],
  },
  {
    slug: "shilin",
    city: "台北市",
    district: "士林區",
    zhName: "士林",
    fullName: "台北市士林區",
    description: "士林區手機維修．i時代 35 分鐘車程．iPhone / Samsung / iPad 維修．免運送回",
    distanceMin: 35,
    highlights: ["35 分鐘車程", "士林夜市鄰近", "免運送回"],
    landmarks: ["士林夜市", "故宮博物院", "天母", "陽明山"],
    popularServices: ["iPhone 螢幕", "電池", "iPad 維修"],
  },
  {
    slug: "beitou",
    city: "台北市",
    district: "北投區",
    zhName: "北投",
    fullName: "台北市北投區",
    description: "北投手機維修．i時代板橋 40 分鐘車程．iPhone / iPad 換螢幕電池．免運到府",
    distanceMin: 40,
    highlights: ["40 分鐘車程", "捷運淡水線直達", "免運送回"],
    landmarks: ["北投溫泉", "新北投站", "復興崗", "關渡"],
    popularServices: ["iPhone 維修", "iPad 螢幕", "電池"],
  },
  {
    slug: "neihu",
    city: "台北市",
    district: "內湖區",
    zhName: "內湖",
    fullName: "台北市內湖區",
    description: "內湖手機維修．i時代板橋 30 分鐘車程．iPhone / MacBook / iPad 認證維修",
    distanceMin: 30,
    highlights: ["30 分鐘車程", "鄰近科技園區", "MacBook 維修"],
    landmarks: ["內湖科技園區", "西湖站", "港墘站", "瑞光路"],
    popularServices: ["iPhone 維修", "MacBook", "iPad"],
  },
  {
    slug: "nangang",
    city: "台北市",
    district: "南港區",
    zhName: "南港",
    fullName: "台北市南港區",
    description: "南港手機維修．i時代 35 分鐘車程．iPhone / Samsung / iPad 維修．免運送回",
    distanceMin: 35,
    highlights: ["35 分鐘車程", "南港車站鄰近", "免運送回"],
    landmarks: ["南港車站", "南港軟體園區", "中信總部", "經貿園區"],
    popularServices: ["iPhone 維修", "MacBook", "Samsung"],
  },
];

export function getAreaBySlug(slug: string): LocalArea | undefined {
  return LOCAL_AREAS.find(a => a.slug === slug);
}
